#!/bin/zsh

# enviormental vars
export BROWSER="firefox"
export TERMINAL="st"
export EDITOR="nvim"
export READER="zathura"

# path
PATH=~/.local/bin:$PATH

# nvm
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
