#!/bin/zsh

# enviormental vars
export BROWSER="firefox"
export TERMINAL="st"
export EDITOR="nvim"
export READER="zathura"

# path
PATH=~/.local/bin:$PATH

# nvm
alias lnvm='export NVM_DIR="$HOME/.config/nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
